apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      #initContainers:
      #  - name: init
      #    image: busybox
      #    imagePullPolicy: IfNotPresent
      #    command: [ "sh", "-c"]
      #    args:
      #    -   echo -en '\n';
      #        echo Asia/Shanghai > /etc/timezone;
      #        echo 8096 > /proc/sys/net/core/somaxconn;
      #    securityContext:
      #      privileged: true
      containers:
        - name: nginx
          image: nginx:1.14.1
          #image: uhub.service.ucloud.cn/dk8s/nginx:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 0.5
              memory: 64Mi
            requests:
              cpu: 0.1
              memory: 16Mi
          ports:
            - name: nginx80
              containerPort: 80
              protocol: TCP
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          lifecycle:
            postStart:
              exec:
                command:
                  - 'pwd'
            preStop:
              exec:
                command:
                  - /bin/bash
                  - -c
                  - |
                    echo "Exit ... "
                    exit 0
          volumeMounts:
            - name: time
              mountPath: /etc/localtime
              readOnly: true
          securityContext:
            privileged: false
            capabilities:
              add:
                - NET_ADMIN
      volumes:
        - name: time
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: false
      hostIPC: false
      hostPID: false
      restartPolicy: Always
      schedulerName: default-scheduler
      hostAliases:
      - ip: "10.10.10.10"
        hostnames:
        - "registry.test.cn"
